import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoginBtn from "./LoginBtn.js"
import Link from "next/link";
import { authOptions } from "./api/auth/[...nextauth]/route.js";
import { getServerSession } from "next-auth";
import SessionWrapper from "./SessionWrapper.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (session) {
    console.log('세션출력' + JSON.stringify(session));
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionWrapper>
          <div className="navbar">
              <Link href="/" className="logo">BSSM board</Link>
              <Link href="/list">글목록</Link>
              {session ? (
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <span>안녕하세요, {session.user.name || session.user.email}님</span>
                  <LoginBtn/>
                </div>
              ) : (
                <LoginBtn/>
              )}
          </div>
          {children}
        </SessionWrapper>
      </body>

    </html>
  );
}
